### ISSUE TITLE
Google Play services resources were not found.

### ISSUE THREAD

**Issue by nuno** [deckameron/Ti.Android.Admob#1]
Hello, im try test you module but got this message.
[ERROR] GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.

**Comment by deckameron** [comment]
Hello Nuno,

Please add this line to your <application> tag.

`<meta-data android:name="com.google.android.gms.version" android:value="9683000"/>`

Please tell me if it worked for you. :-)

**Comment by nuno** [comment]
Hey **deckameron**, sorry what tag? on **tiapp.xml**?

**I have some questions:**  :)

 1) this module works ok with sdk 5.5.1.GA? 
 2) the admob configuration on the google admin site, there is anything especial to take care?   :)
 3) the smartBanner works good? 

I ask this because I need my ads with 300x280  but all I get is regular banners.  As a side note on ios i get all work as expected with **ti.admob** module.
Thanks  a lot!  @deckameron   👍

**Comment by deckameron** [comment]
I am so sorry Nuno! I wrote it fast and "skipped" the tag, it is "application". Just like this:

``` XML
<android xmlns:android="http://schemas.android.com/apk/res/android">
    <application>
        <meta-data android:name="com.google.android.gms.version" android:value="9683000"/>
    </application>
</android>
```

1) this module works ok with sdk 5.5.1.GA? 
Yes it does! :-)
2) the admob configuration on the google admin site, there is anything especial to take care? :)
Only to use the Native Ads. You would need to create a position and format the CSS on the Google Admod dashboard.
3) The smartBanner works good?
Yes, it does!

I really think this module will help you a lot.
I will make the code available as soon as possible. (I am still learning how to use GitHub)

**Comment by nuno** [comment]
Thank you so much @deckameron, let me know if you need any help commit and push the code to github!

**Comment by deckameron** [comment]
Thank you @nuno!
I just made it. :-)

I have just tested the SmartBanner but it is not working properly. :(
Apparently it only showing 320x50 ads.
I will have to investigate it.

**Comment by nuno** [comment]
Do you know what this is? http://sharebucketapp.com/ZWNlNzJmNDI4ZTEzYTA0

```
var nativeAd = Admob.createView({
    adSizeType: 'NATIVE',
    height : 250,
    width : 300,
    publisherId: 'ca-app-pub-6899365325952326/7757552092', //USE YOUR PUBLISHER ID HERE
    testing: true
}); 
```

**Comment by deckameron** [comment]
I guess I know!
Edit you tiapp.xml and use this inside your "Application" tag again.

``` XML
<activity android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:name="com.google.android.gms.ads.AdActivity"/>
```

**Comment by deckameron** [comment]
Hi @nuno ,
Did it work?

**Comment by rcampbell75** [comment]
Just wanted to say Thank you to deckameron for the module, it works perfectly with SDK 5.5.1GA!  

If you would like some help in writing up documentation or anything for it, let me know.

**Comment by nuno** [comment]
@deckameron sorry for my delay, yes it worked but all must be inside of <manifest> tags. 

```
<android xmlns:android="http://schemas.android.com/apk/res/android">
<manifest>
            <application>
              <meta-data android:name="com.google.android.gms.version" android:value="9683000"/>
          </application>
          <activity android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:name="com.google.android.gms.ads.AdActivity"/>
</manifest>
</android>
```

Thanks.

**Comment by deckameron** [comment]
Happy to know it worked, @nuno!
Thank you!
