### ISSUE TITLE
Support to GDPR

### ISSUE THREAD

**Issue by ottopic** [deckameron/Ti.Android.Admob#10]
Hello,
are you work upgrading library to support GDPR consent requests ?
You are doing a great work with this module.

**Comment by deckameron** [comment]
Hi @ottopic 
Yes! I plan to do it, but not right now. I am loaded with stuff at work and don't have the time.
Maybe in a few weeks.

**Comment by ottopic** [comment]
Thank you for your reply @deckameron  !
Have you ever consider to merge into ti.admob project contributing with yours Android interstitial implementation?

Best regards.

**Comment by deckameron** [comment]
@ottopic,
I have never considered merging with appcelerator modules, but I will as soon as I finish what you asked. :)

**Comment by deckameron** [comment]
@ottopic Could you test [version 3.0.4](https://github.com/deckameron/Ti.Android.Admob/blob/master/android/dist/ti.android.admob-android-3.0.4.zip?raw=true), please?

Just follow [appcelerator admob module docs](https://github.com/appcelerator-modules/ti.admob/blob/master/android/documentation/index.md) for now. I will update the my docs some other time.

**Comment by ottopic** [comment]
Thank you @deckameron , I'll try ASAP.

**Comment by ottopic** [comment]
@deckameron I tried 3.0.4 to request GDPR consent but get in error.
If I understood what you wrote I have to use ti.admob configuration to request consent.

Uncaught TypeError: Admob.requestConsentInfoUpdateForPublisherIdentifiers is not a function

```
function requestConsentInfo(call) {
    Admob.requestConsentInfoUpdateForPublisherIdentifiers({
        publisherIdentifiers: ['pub-xxxxxxxxxxxxxxxxx'],
        callback: function (e) {
            log.info(JSON.stringify(e));
            if(e.success && call != '') eval(call + '()');
        }
    });
}
```

**Comment by deckameron** [comment]
@ottopic I see.
I must have made a mistake on my code. I will investigate asap.

**Comment by ottopic** [comment]
Hi @deckameron , have you tried to find mistake? Can I help you ?

**Comment by deckameron** [comment]
Hi @ottopic,
I am sorry! I could not fix it last week. I was in a middle of the end of the world putting out fires!
I will be available again on next weekend and I promise you I will implement it correctly.

**Comment by deckameron** [comment]
Hi @ottopic,
Could you test [3.0.5](https://github.com/deckameron/Ti.Android.Admob/blob/master/android/dist/ti.android.admob-android-3.0.5.zip?raw=true), please?

**Comment by ottopic** [comment]
Thank you @deckameron .
It's seems there is a syntax error:

`[ERROR] :  SyntaxError: Missing catch or finally after try`

**Comment by deckameron** [comment]
@ottopic I see!
What method was it? requestConsentInfoUpdateForPublisherIdentifiers?

**Comment by ottopic** [comment]
Problem should be simulator and liveview, I'll test on device asap.

**Comment by ottopic** [comment]
Running on device there isn't syntax error, but I don't see popup, I get error `[ERROR] :  AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/consentform.html
`.

Do you have example?

**Comment by Astrovic** [comment]
To personally manage the GDPR form, it would be useful to add a Bundle extras to all types of ads, as specified in the documentation https://developers.google.com/admob/android/eu-consent#forward_consent_to_the_google_mobile_ads_sdk, to be able to pass for example `extras: {'npa':'1'}` to disable personalized ads. As was done in ti.admob module (https://github.com/appcelerator-modules/ti.admob/blob/63426867b1ed957135a29405a4d8b7097b81770a/android/src/ti/admob/View.java#L71)

**Comment by deckameron** [comment]
Hi @Astrovic 
Thank you! I will implement asap.

**Comment by deckameron** [comment]
Hi @Astrovic 
Could you try [this version](https://github.com/deckameron/Ti.Android.Admob/blob/master/android/dist/ti.android.admob-android-5.0.1.zip?raw=true), please?

**Comment by Astrovic** [comment]
Hi @deckameron it seems to work properly, well done!!

**Comment by deckameron** [comment]
Thank you @Astrovic !
