### ISSUE TITLE
Bluetooth permission?

### ISSUE THREAD

**Issue by kerberosargos** [deckameron/Ti.Android.Admob#13]
Hello @deckameron is your module really need "android.permission.BLUETOOTH"?

**Comment by deckameron** [comment]
Hi @kerbooo 

Because there is now the possibility of using video in the Ads, it is necessary to have Bluetooth permission.

When I remove the permission and run a example of Native Advanced Video, I get this warn:

```javascript
[WARN] :   cr_media: Requires BLUETOOTH permission
```

**Comment by kerberosargos** [comment]
Thank you very much.

Douglas Alves <notifications@github.com>, 9 Oca 2019 Çar, 14:53 tarihinde
şunu yazdı:

**Comment by deckameron** [comment]
You are welcome! :)
