### ISSUE TITLE
Android device back button close prevent?

### ISSUE THREAD

**Issue by kerberosargos** [deckameron/Ti.Android.Admob#14]
Hello again, can I prevent android device back button when Interstitial ads showing? 

Thank you very much for your great module.

**Comment by deckameron** [comment]
Hi @kerbooo ,
AdMob creates its own Activity on top of yours, so it has its own implementation of onBackPressed(), which means that you don't have control of anything that happens once you call interstitial.show(); until AdMob gives control back to your activity.
