### ISSUE TITLE
[Android] build fails on Ti SDK 9 cause of new gradle system

### ISSUE THREAD

**Issue by Astrovic** [deckameron/Ti.Android.Admob#17]
In order to continue using Ti.Android.Admob on Android with TiSDK>9, it would be necessary to update to use gradle (https://wiki.appcelerator.org/display/guides2/Android+Module+Upgrade+Guide#AndroidModuleUpgradeGuide-MigrationtoSDK9.0.0)

**Comment by deckameron** [comment]
Sorry it took so long. I am swamped!
[Here](https://github.com/deckameron/Ti.Android.Admob/blob/master/android/dist/ti.android.admob-android-6.0.1.zip) it is.

**Comment by Astrovic** [comment]
Hi @deckameron! Finally I got to test the update. Seems to work perfectly, great job!
Could you update the code on the repo? So we can autonomously build the module in case we want to add or update the dependencies :)
