### ISSUE TITLE
SDK 6.0.0 Support?

### ISSUE THREAD

**Issue by rcampbell75** [deckameron/Ti.Android.Admob#3]
Unable to use module with 6.0.0.GA SDK.  Will it be updated to support 6.0.0.GA SDK?

**Comment by deckameron** [comment]
Hi @rcampbell75 
I have been trying to make this module compatible with 6.0.0.GA but unfortunately I don't know how.
I have recreated the module using 6.0.0.GA and I can add the module to a project normally, but when I compile, I get this error:

`[WARN] :   Could not find a valid Titanium module id=ti.android.admob version=latest platform=android deploy-type=development
[ERROR] :  Found incompatible Titanium Modules:
[ERROR] :     id: ti.android.admob	 version: 1.0	 platform: android	 min sdk: 6.0.0.GA` 

I will keep digging but I am kind of lost right now.

**Comment by albwebbergate** [comment]
> I have been trying to make this module compatible with 6.0.0.GA but unfortunately I don't know how.
I have recreated the module using 6.0.0.GA and I can add the module to a project normally, but when I compile [...]

Sorry @deckameron Have you try to follow this guide? [Rebuilding modules for Titanium 6](http://skypanther.com/2016/10/rebuilding-modules-for-titanium-6/), Skypanther is a very expert guy on appcelerator

**Comment by deckameron** [comment]
Thanks @albwebbergate!
I have tried it but if remove "armeabi" from architectures on manifest file, it won't compile.
I get this error:

check.build.arch:
        [echo] Architectures in manifest: armeabi-v7a;x86
        [echo] Compiled binary architectures: armeabi;armeabi-v7a;x86

BUILD FAILED
/Users/douglasalves/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/module/android/build.xml:376: The following error occurred while executing this line:
/Users/douglasalves/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/module/android/build.xml:378: There is discrepancy between the architectures specified in manifest and compiled binary.

[EDIT]
I have managed to compile it, but none of my projects seems to recognize it. Could you try please? 
Just download [version 2.0 from dist folder](https://github.com/deckameron/Ti.Android.Admob/blob/master/android/dist/ti.android.admob-android-2.0.zip?raw=true).

**Comment by albwebbergate** [comment]
`I have managed to compile it, but none of my projects seems to recognize it. Could you try please?
Just download version 2.0 from dist folder.`

No it doesn't work neither with 6.0.0GA nor 6.0.1GA
![appcelerator](https://cloud.githubusercontent.com/assets/15871664/21432855/affb16e8-c86d-11e6-9a25-2b52e15395f3.png)

Instead version 1.0 is recognized by 5.5.1GA

**Comment by deckameron** [comment]
Hi @albwebbergate,

I think [this new upload](https://github.com/deckameron/Ti.Android.Admob/blob/master/android/dist/ti.android.admob-android-2.0.zip?raw=true) will work. :-)

**Comment by deckameron** [comment]
Hi @albwebbergate!
Did you manage to get the new version working?

**Comment by albwebbergate** [comment]
`Hi @albwebbergate!
Did you manage to get the new version working?`

The new version is recognized with all 5.5.1, 6.0.0 and 6.0.1 Titanium SDK.
But I have to use 5.5.1GA cause incompatibilites with other modules, so I didn't test the new version.

**Comment by deckameron** [comment]
I see! I will close this issue then.
I hope the other modules developers update theirs. :)
