### ISSUE TITLE
Error during build: jarsigner: unable to sign jar

### ISSUE THREAD

**Issue by arifje** [deckameron/Ti.Android.Admob#4]
Full error:

[ERROR] :  Failed to sign apk:
[ERROR] :  jarsigner: unable to sign jar: java.util.zip.ZipException: duplicate entry: org/appcelerator/titanium/gen/bindings.json

I think this happens because we use multipe modules with google-play-services.

Any idea how to fix this?

Working on SDK 6.0.2.GA.

**Comment by arifje** [comment]
Solved it by running: 

zip -d your-module-jar-file.jar org/appcelerator/titanium/gen/bindings.json

**Comment by deckameron** [comment]
Sorry I took so long to answer.
But I am glad you found a solution and shared with us. 👍
