### ISSUE TITLE
No support for multiple adsizes

### ISSUE THREAD

**Issue by arifje** [deckameron/Ti.Android.Admob#5]
See: https://developers.google.com/mobile-ads-sdk/docs/dfp/android/banner#multiple

Would be great ;-)

**Comment by deckameron** [comment]
Hi @skoften ,

Are you talking about these adsizes?
<img width="865" alt="screen shot 2017-03-14 at 18 44 19" src="https://cloud.githubusercontent.com/assets/4404942/23923689/66b97ff6-08e6-11e7-9244-8eed6aa71044.png">

If so, they are all already implemented as you can see [here](https://github.com/deckameron/Ti.Android.Admob/blob/master/android/src/ti/android/admob/View.java)

Use it like this:
```
var bannerAd = admob.createView({
    top: 0,
    adSizeType: 'BANNER', //RECTANGLE, FULLBANNER, LEADERBOARD, SMART
    publisherId: 'ca-app-pub-xxxxxxxxxxxxx/xxxxxxx', //USE YOUR PUBLISHER ID HERE
    testing: true
}); 
window.add(bannerAd);
```

**Comment by deckameron** [comment]
Did you manage to get it working @skoften?

**Comment by arifje** [comment]
Hi Deckameron,

Sorry for the late reply, but that's not what I meant with multiple adSizes. I need to pass multiple adsizes as an argument to the view, because our DFP-tag can serve multiple ad formats: it can be a 320x50, but also 320x100. The view needs to adapt when one of these banners is displayed/served.

From my previous link: 

_DFP allows you to specify multiple ad sizes which may be eligible to serve into a PublisherAdView. Before implementing this feature in the SDK, create a line item targeting the same ad unit which is associated with different size creatives._

The Ti.DFP module also was updated with this feature a while ago: https://github.com/jpriebe/ti.dfp/pull/7

**Comment by deckameron** [comment]
I am so sorry @skoften. I didn't understand it right.
I will implement it as soon as possible.

**Comment by arifje** [comment]
Awesome!

**Comment by deckameron** [comment]
Just implemented it!

**Comment by arifje** [comment]
nice!
