### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by varfid** [deckameron/Ti.Android.Admob#6]
Hi, I am using your module (version 2.0) in Titanium (version 6.1.2.GA), but when i run my app on Android i receive this error at execution time:

`[ERROR] :  V8Exception: Exception occurred at ti:/module.js:305: Uncaught Error: Requested module not found: ti.android.admob
`

My code is the same as your example, i only change my admob publisher id

Is anybody having the same problem?
Thanks in advance

**Comment by deckameron** [comment]
Hi @varfid 
Did you manage to solve the issue?
Unfortunately I was not able reproduce it. :(

**Comment by varfid** [comment]
Hi @deckameron I didn't solve this issue yet
Tell me please if i am using the correct version module:
I am using module version 2.0. that I downloaded from android/dist folder. Is correct this?

Thanks
