### ISSUE TITLE
Module does not work with SDK less than 7.0.0.GA

### ISSUE THREAD

**Issue by SilvioLuis** [deckameron/Ti.Android.Admob#9]
Hello!

I have a whole project based on version 6.2.2.GA of Appcelerator ... I can not upgrade yet, as it has some modules that do not support 7.0.0.GA.

Does your module have some version to work with 6.2.2.GA?

Thank you.

![captura de tela 2018-04-20 as 15 09 27](https://user-images.githubusercontent.com/6088371/39066823-dad3a13e-44ac-11e8-873b-55bbd38080d8.png)

**Comment by deckameron** [comment]
Hi @SilvioLuis,

Have you tried [2.0 version](https://github.com/deckameron/Ti.Android.Admob/blob/master/android/dist/ti.android.admob-android-2.0.zip?raw=true)?

**Comment by SilvioLuis** [comment]
Hello @deckameron !

I've already been able to upgrade my modules to version 7.0.0.GA.

The ads usually appear on my app now, and are already on google play.

The problem now is that they appear in the "Test Ad" version and I can not remove it ... The apk is signed right now, and I already put in the Google Play Console that the app contains advertising ... something else I should do ?

I've also tried adding a "testing: false" parameter. I tried to remove the parameter from "testDeviceId" but nothing works ...

Anything I can do to solve this? Thank you.

![admob-test](https://user-images.githubusercontent.com/6088371/39369139-df2c039c-4a11-11e8-9f11-0295e5ca17a0.png)

**Comment by deckameron** [comment]
Hi @SilvioLuis,
Could you show me a bit o code please?
Did you download the app from Google Play on different devices?

**Comment by SilvioLuis** [comment]
Hi @deckameron,

Thanks a lot for the tip, I actually tested on other devices and the ad is running normally in production mode.

**Comment by deckameron** [comment]
@SilvioLuis Glad to know! :-)
